### ISSUE TITLE
contributors image in readme

### ISSUE THREAD

**Issue by Ankurrawat-12** [cg-humanore/hacktoberfest_2022#1]
![image](https://user-images.githubusercontent.com/78417225/194757297-c78387ce-d54f-424e-8cbd-8d332e222c6c.png)
like this

**Comment by Ankurrawat-12** [comment]
assign me this issue

**Comment by cg-humanore** [comment]
ok

**Comment by Ankurrawat-12** [comment]
done
can you merge the pr
